// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package models

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    code, trip_id, user_id, guest_info,
    pickup_info, dropoff_info, seat_codes,
    total_amount, payment_method
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at
`

type CreateBookingParams struct {
	Code          string          `json:"code"`
	TripID        int64           `json:"tripId"`
	UserID        *int64          `json:"userId"`
	GuestInfo     json.RawMessage `json:"guestInfo"`
	PickupInfo    json.RawMessage `json:"pickupInfo"`
	DropoffInfo   json.RawMessage `json:"dropoffInfo"`
	SeatCodes     []string        `json:"seatCodes"`
	TotalAmount   pgtype.Numeric  `json:"totalAmount"`
	PaymentMethod *string         `json:"paymentMethod"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.Code,
		arg.TripID,
		arg.UserID,
		arg.GuestInfo,
		arg.PickupInfo,
		arg.DropoffInfo,
		arg.SeatCodes,
		arg.TotalAmount,
		arg.PaymentMethod,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByCode = `-- name: GetBookingByCode :one
SELECT id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at FROM bookings WHERE code = $1
`

func (q *Queries) GetBookingByCode(ctx context.Context, code string) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByCode, code)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT b.id, b.code, b.trip_id, b.user_id, b.guest_info, b.pickup_info, b.dropoff_info, b.seat_codes, b.total_amount, b.status, b.payment_method, b.created_at, b.updated_at, t.departure_time, t.arrival_time,
       o.name as origin_name, d.name as destination_name
FROM bookings b
JOIN trips t ON b.trip_id = t.id
JOIN locations o ON t.origin_id = o.id
JOIN locations d ON t.destination_id = d.id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByUserParams struct {
	UserID *int64 `json:"userId"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListBookingsByUserRow struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	TripID          int64              `json:"tripId"`
	UserID          *int64             `json:"userId"`
	GuestInfo       json.RawMessage    `json:"guestInfo"`
	PickupInfo      json.RawMessage    `json:"pickupInfo"`
	DropoffInfo     json.RawMessage    `json:"dropoffInfo"`
	SeatCodes       []string           `json:"seatCodes"`
	TotalAmount     pgtype.Numeric     `json:"totalAmount"`
	Status          *string            `json:"status"`
	PaymentMethod   *string            `json:"paymentMethod"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	DepartureTime   pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime     pgtype.Timestamptz `json:"arrivalTime"`
	OriginName      string             `json:"originName"`
	DestinationName string             `json:"destinationName"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]ListBookingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByUserRow{}
	for rows.Next() {
		var i ListBookingsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TripID,
			&i.UserID,
			&i.GuestInfo,
			&i.PickupInfo,
			&i.DropoffInfo,
			&i.SeatCodes,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.OriginName,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET 
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID     int64   `json:"id"`
	Status *string `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
