// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminBookings = `-- name: CountAdminBookings :one
SELECT COUNT(*)
FROM bookings b
WHERE ($1::text = '' OR b.status = $1)
  AND ($2::bigint = 0 OR b.trip_id = $2)
  AND (
    $3::text = ''
    OR b.code ILIKE '%' || $3 || '%'
    OR COALESCE(b.guest_info->>'name', '') ILIKE '%' || $3 || '%'
    OR COALESCE(b.guest_info->>'phone', '') ILIKE '%' || $3 || '%'
  )
`

type CountAdminBookingsParams struct {
	Column1 string `json:"column1"`
	Column2 int64  `json:"column2"`
	Column3 string `json:"column3"`
}

func (q *Queries) CountAdminBookings(ctx context.Context, arg CountAdminBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminBookings, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByTrip = `-- name: CountBookingsByTrip :one
SELECT COUNT(*) FROM bookings WHERE trip_id = $1 AND status IN ('pending', 'paid')
`

func (q *Queries) CountBookingsByTrip(ctx context.Context, tripID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByTrip, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByUser = `-- name: CountBookingsByUser :one
SELECT COUNT(*) FROM bookings WHERE user_id = $1
`

func (q *Queries) CountBookingsByUser(ctx context.Context, userID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRefundPendingBookings = `-- name: CountRefundPendingBookings :one
SELECT COUNT(*) FROM bookings WHERE status = 'refund_pending'
`

func (q *Queries) CountRefundPendingBookings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRefundPendingBookings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    code, trip_id, user_id, guest_info,
    pickup_info, dropoff_info, seat_codes,
    total_amount, payment_method
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note
`

type CreateBookingParams struct {
	Code          string          `json:"code"`
	TripID        int64           `json:"tripId"`
	UserID        *int64          `json:"userId"`
	GuestInfo     json.RawMessage `json:"guestInfo"`
	PickupInfo    json.RawMessage `json:"pickupInfo"`
	DropoffInfo   json.RawMessage `json:"dropoffInfo"`
	SeatCodes     []string        `json:"seatCodes"`
	TotalAmount   pgtype.Numeric  `json:"totalAmount"`
	PaymentMethod *string         `json:"paymentMethod"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.Code,
		arg.TripID,
		arg.UserID,
		arg.GuestInfo,
		arg.PickupInfo,
		arg.DropoffInfo,
		arg.SeatCodes,
		arg.TotalAmount,
		arg.PaymentMethod,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const createBookingWithExpiry = `-- name: CreateBookingWithExpiry :one
INSERT INTO bookings (
    code, trip_id, user_id, guest_info,
    pickup_info, dropoff_info, seat_codes,
    total_amount, payment_method, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note
`

type CreateBookingWithExpiryParams struct {
	Code          string             `json:"code"`
	TripID        int64              `json:"tripId"`
	UserID        *int64             `json:"userId"`
	GuestInfo     json.RawMessage    `json:"guestInfo"`
	PickupInfo    json.RawMessage    `json:"pickupInfo"`
	DropoffInfo   json.RawMessage    `json:"dropoffInfo"`
	SeatCodes     []string           `json:"seatCodes"`
	TotalAmount   pgtype.Numeric     `json:"totalAmount"`
	PaymentMethod *string            `json:"paymentMethod"`
	ExpiresAt     pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateBookingWithExpiry(ctx context.Context, arg CreateBookingWithExpiryParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBookingWithExpiry,
		arg.Code,
		arg.TripID,
		arg.UserID,
		arg.GuestInfo,
		arg.PickupInfo,
		arg.DropoffInfo,
		arg.SeatCodes,
		arg.TotalAmount,
		arg.PaymentMethod,
		arg.ExpiresAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const getAdminBookingRevenueSeries = `-- name: GetAdminBookingRevenueSeries :many
WITH day_series AS (
    SELECT generate_series(
        (CURRENT_DATE - (($1::int - 1) * INTERVAL '1 day'))::date,
        CURRENT_DATE::date,
        INTERVAL '1 day'
    )::date AS day
)
SELECT
    ds.day,
    COUNT(b.id)::bigint AS total_bookings,
    COUNT(b.id) FILTER (WHERE b.status = 'paid')::bigint AS paid_bookings,
    COUNT(b.id) FILTER (WHERE b.status = 'pending')::bigint AS unpaid_bookings,
    COALESCE(SUM(b.total_amount) FILTER (WHERE b.status = 'paid'), 0)::numeric AS paid_revenue
FROM day_series ds
LEFT JOIN bookings b ON DATE(b.created_at) = ds.day
GROUP BY ds.day
ORDER BY ds.day ASC
`

type GetAdminBookingRevenueSeriesRow struct {
	Day            pgtype.Date    `json:"day"`
	TotalBookings  int64          `json:"totalBookings"`
	PaidBookings   int64          `json:"paidBookings"`
	UnpaidBookings int64          `json:"unpaidBookings"`
	PaidRevenue    pgtype.Numeric `json:"paidRevenue"`
}

func (q *Queries) GetAdminBookingRevenueSeries(ctx context.Context, dollar_1 int32) ([]GetAdminBookingRevenueSeriesRow, error) {
	rows, err := q.db.Query(ctx, getAdminBookingRevenueSeries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminBookingRevenueSeriesRow{}
	for rows.Next() {
		var i GetAdminBookingRevenueSeriesRow
		if err := rows.Scan(
			&i.Day,
			&i.TotalBookings,
			&i.PaidBookings,
			&i.UnpaidBookings,
			&i.PaidRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminBookingStats = `-- name: GetAdminBookingStats :one
SELECT
    COUNT(*)::bigint AS total_bookings,
    COUNT(*) FILTER (WHERE status = 'pending')::bigint AS unpaid_bookings,
    COUNT(*) FILTER (WHERE status = 'paid')::bigint AS paid_bookings,
    COUNT(*) FILTER (WHERE status = 'refund_pending')::bigint AS refund_pending_bookings,
    COUNT(*) FILTER (WHERE status = 'cancelled')::bigint AS cancelled_bookings,
    COALESCE(SUM(total_amount) FILTER (WHERE status = 'paid'), 0)::numeric AS paid_revenue,
    COALESCE(SUM(total_amount) FILTER (WHERE status = 'pending'), 0)::numeric AS unpaid_revenue,
    COUNT(DISTINCT trip_id) FILTER (WHERE status IN ('pending', 'paid', 'refund_pending'))::bigint AS active_trip_count
FROM bookings
`

type GetAdminBookingStatsRow struct {
	TotalBookings         int64          `json:"totalBookings"`
	UnpaidBookings        int64          `json:"unpaidBookings"`
	PaidBookings          int64          `json:"paidBookings"`
	RefundPendingBookings int64          `json:"refundPendingBookings"`
	CancelledBookings     int64          `json:"cancelledBookings"`
	PaidRevenue           pgtype.Numeric `json:"paidRevenue"`
	UnpaidRevenue         pgtype.Numeric `json:"unpaidRevenue"`
	ActiveTripCount       int64          `json:"activeTripCount"`
}

func (q *Queries) GetAdminBookingStats(ctx context.Context) (GetAdminBookingStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminBookingStats)
	var i GetAdminBookingStatsRow
	err := row.Scan(
		&i.TotalBookings,
		&i.UnpaidBookings,
		&i.PaidBookings,
		&i.RefundPendingBookings,
		&i.CancelledBookings,
		&i.PaidRevenue,
		&i.UnpaidRevenue,
		&i.ActiveTripCount,
	)
	return i, err
}

const getBookingByCode = `-- name: GetBookingByCode :one
SELECT id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note FROM bookings WHERE code = $1
`

func (q *Queries) GetBookingByCode(ctx context.Context, code string) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByCode, code)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const getBookingForPayment = `-- name: GetBookingForPayment :one

SELECT id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note FROM bookings WHERE id = $1 FOR UPDATE NOWAIT
`

func (q *Queries) GetBookingForPayment(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingForPayment, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const getExpiredPendingBookings = `-- name: GetExpiredPendingBookings :many
SELECT id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note FROM bookings 
WHERE status = 'pending' AND expires_at < NOW()
FOR UPDATE SKIP LOCKED
LIMIT $1
`

func (q *Queries) GetExpiredPendingBookings(ctx context.Context, limit int32) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getExpiredPendingBookings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TripID,
			&i.UserID,
			&i.GuestInfo,
			&i.PickupInfo,
			&i.DropoffInfo,
			&i.SeatCodes,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.RefundedAt,
			&i.RefundReference,
			&i.RefundNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveBookingsByTrip = `-- name: ListActiveBookingsByTrip :many
SELECT b.id, b.code, b.trip_id, b.user_id, b.guest_info, b.pickup_info, b.dropoff_info, b.seat_codes, b.total_amount, b.status, b.payment_method, b.created_at, b.updated_at, b.expires_at, b.refunded_at, b.refund_reference, b.refund_note, t.departure_time, t.arrival_time,
       o.name as origin_name, d.name as destination_name
FROM bookings b
JOIN trips t ON b.trip_id = t.id
JOIN locations o ON t.origin_id = o.id
JOIN locations d ON t.destination_id = d.id
WHERE b.trip_id = $1
  AND b.status IN ('pending', 'paid', 'refund_pending')
ORDER BY b.created_at DESC
`

type ListActiveBookingsByTripRow struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	TripID          int64              `json:"tripId"`
	UserID          *int64             `json:"userId"`
	GuestInfo       json.RawMessage    `json:"guestInfo"`
	PickupInfo      json.RawMessage    `json:"pickupInfo"`
	DropoffInfo     json.RawMessage    `json:"dropoffInfo"`
	SeatCodes       []string           `json:"seatCodes"`
	TotalAmount     pgtype.Numeric     `json:"totalAmount"`
	Status          *string            `json:"status"`
	PaymentMethod   *string            `json:"paymentMethod"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	ExpiresAt       pgtype.Timestamptz `json:"expiresAt"`
	RefundedAt      pgtype.Timestamptz `json:"refundedAt"`
	RefundReference *string            `json:"refundReference"`
	RefundNote      *string            `json:"refundNote"`
	DepartureTime   pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime     pgtype.Timestamptz `json:"arrivalTime"`
	OriginName      string             `json:"originName"`
	DestinationName string             `json:"destinationName"`
}

func (q *Queries) ListActiveBookingsByTrip(ctx context.Context, tripID int64) ([]ListActiveBookingsByTripRow, error) {
	rows, err := q.db.Query(ctx, listActiveBookingsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBookingsByTripRow{}
	for rows.Next() {
		var i ListActiveBookingsByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TripID,
			&i.UserID,
			&i.GuestInfo,
			&i.PickupInfo,
			&i.DropoffInfo,
			&i.SeatCodes,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.RefundedAt,
			&i.RefundReference,
			&i.RefundNote,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.OriginName,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSeatCodesByUserTrip = `-- name: ListActiveSeatCodesByUserTrip :many
SELECT DISTINCT seat_codes.seat_code::text AS seat_code
FROM bookings b
CROSS JOIN LATERAL unnest(COALESCE(b.seat_codes, '{}'::text[])) AS seat_codes(seat_code)
WHERE b.user_id = $1
  AND b.trip_id = $2
  AND b.status IN ('pending', 'paid', 'refund_pending')
`

type ListActiveSeatCodesByUserTripParams struct {
	UserID *int64 `json:"userId"`
	TripID int64  `json:"tripId"`
}

func (q *Queries) ListActiveSeatCodesByUserTrip(ctx context.Context, arg ListActiveSeatCodesByUserTripParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveSeatCodesByUserTrip, arg.UserID, arg.TripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var seat_code string
		if err := rows.Scan(&seat_code); err != nil {
			return nil, err
		}
		items = append(items, seat_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminBookings = `-- name: ListAdminBookings :many
SELECT b.id, b.code, b.trip_id, b.user_id, b.guest_info, b.pickup_info, b.dropoff_info, b.seat_codes, b.total_amount, b.status, b.payment_method, b.created_at, b.updated_at, b.expires_at, b.refunded_at, b.refund_reference, b.refund_note, t.departure_time, t.arrival_time,
       o.name as origin_name, d.name as destination_name
FROM bookings b
JOIN trips t ON b.trip_id = t.id
JOIN locations o ON t.origin_id = o.id
JOIN locations d ON t.destination_id = d.id
WHERE ($1::text = '' OR b.status = $1)
  AND ($2::bigint = 0 OR b.trip_id = $2)
  AND (
    $3::text = ''
    OR b.code ILIKE '%' || $3 || '%'
    OR COALESCE(b.guest_info->>'name', '') ILIKE '%' || $3 || '%'
    OR COALESCE(b.guest_info->>'phone', '') ILIKE '%' || $3 || '%'
  )
ORDER BY b.created_at DESC
LIMIT $4 OFFSET $5
`

type ListAdminBookingsParams struct {
	Column1 string `json:"column1"`
	Column2 int64  `json:"column2"`
	Column3 string `json:"column3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListAdminBookingsRow struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	TripID          int64              `json:"tripId"`
	UserID          *int64             `json:"userId"`
	GuestInfo       json.RawMessage    `json:"guestInfo"`
	PickupInfo      json.RawMessage    `json:"pickupInfo"`
	DropoffInfo     json.RawMessage    `json:"dropoffInfo"`
	SeatCodes       []string           `json:"seatCodes"`
	TotalAmount     pgtype.Numeric     `json:"totalAmount"`
	Status          *string            `json:"status"`
	PaymentMethod   *string            `json:"paymentMethod"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	ExpiresAt       pgtype.Timestamptz `json:"expiresAt"`
	RefundedAt      pgtype.Timestamptz `json:"refundedAt"`
	RefundReference *string            `json:"refundReference"`
	RefundNote      *string            `json:"refundNote"`
	DepartureTime   pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime     pgtype.Timestamptz `json:"arrivalTime"`
	OriginName      string             `json:"originName"`
	DestinationName string             `json:"destinationName"`
}

func (q *Queries) ListAdminBookings(ctx context.Context, arg ListAdminBookingsParams) ([]ListAdminBookingsRow, error) {
	rows, err := q.db.Query(ctx, listAdminBookings,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminBookingsRow{}
	for rows.Next() {
		var i ListAdminBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TripID,
			&i.UserID,
			&i.GuestInfo,
			&i.PickupInfo,
			&i.DropoffInfo,
			&i.SeatCodes,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.RefundedAt,
			&i.RefundReference,
			&i.RefundNote,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.OriginName,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT b.id, b.code, b.trip_id, b.user_id, b.guest_info, b.pickup_info, b.dropoff_info, b.seat_codes, b.total_amount, b.status, b.payment_method, b.created_at, b.updated_at, b.expires_at, b.refunded_at, b.refund_reference, b.refund_note, t.departure_time, t.arrival_time,
       o.name as origin_name, d.name as destination_name
FROM bookings b
JOIN trips t ON b.trip_id = t.id
JOIN locations o ON t.origin_id = o.id
JOIN locations d ON t.destination_id = d.id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByUserParams struct {
	UserID *int64 `json:"userId"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListBookingsByUserRow struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	TripID          int64              `json:"tripId"`
	UserID          *int64             `json:"userId"`
	GuestInfo       json.RawMessage    `json:"guestInfo"`
	PickupInfo      json.RawMessage    `json:"pickupInfo"`
	DropoffInfo     json.RawMessage    `json:"dropoffInfo"`
	SeatCodes       []string           `json:"seatCodes"`
	TotalAmount     pgtype.Numeric     `json:"totalAmount"`
	Status          *string            `json:"status"`
	PaymentMethod   *string            `json:"paymentMethod"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	ExpiresAt       pgtype.Timestamptz `json:"expiresAt"`
	RefundedAt      pgtype.Timestamptz `json:"refundedAt"`
	RefundReference *string            `json:"refundReference"`
	RefundNote      *string            `json:"refundNote"`
	DepartureTime   pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime     pgtype.Timestamptz `json:"arrivalTime"`
	OriginName      string             `json:"originName"`
	DestinationName string             `json:"destinationName"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]ListBookingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByUserRow{}
	for rows.Next() {
		var i ListBookingsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TripID,
			&i.UserID,
			&i.GuestInfo,
			&i.PickupInfo,
			&i.DropoffInfo,
			&i.SeatCodes,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.RefundedAt,
			&i.RefundReference,
			&i.RefundNote,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.OriginName,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundPendingBookings = `-- name: ListRefundPendingBookings :many
SELECT b.id, b.code, b.trip_id, b.user_id, b.guest_info, b.pickup_info, b.dropoff_info, b.seat_codes, b.total_amount, b.status, b.payment_method, b.created_at, b.updated_at, b.expires_at, b.refunded_at, b.refund_reference, b.refund_note, t.departure_time, t.arrival_time,
       o.name as origin_name, d.name as destination_name
FROM bookings b
JOIN trips t ON b.trip_id = t.id
JOIN locations o ON t.origin_id = o.id
JOIN locations d ON t.destination_id = d.id
WHERE b.status = 'refund_pending'
ORDER BY b.updated_at ASC
LIMIT $1 OFFSET $2
`

type ListRefundPendingBookingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRefundPendingBookingsRow struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	TripID          int64              `json:"tripId"`
	UserID          *int64             `json:"userId"`
	GuestInfo       json.RawMessage    `json:"guestInfo"`
	PickupInfo      json.RawMessage    `json:"pickupInfo"`
	DropoffInfo     json.RawMessage    `json:"dropoffInfo"`
	SeatCodes       []string           `json:"seatCodes"`
	TotalAmount     pgtype.Numeric     `json:"totalAmount"`
	Status          *string            `json:"status"`
	PaymentMethod   *string            `json:"paymentMethod"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	ExpiresAt       pgtype.Timestamptz `json:"expiresAt"`
	RefundedAt      pgtype.Timestamptz `json:"refundedAt"`
	RefundReference *string            `json:"refundReference"`
	RefundNote      *string            `json:"refundNote"`
	DepartureTime   pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime     pgtype.Timestamptz `json:"arrivalTime"`
	OriginName      string             `json:"originName"`
	DestinationName string             `json:"destinationName"`
}

func (q *Queries) ListRefundPendingBookings(ctx context.Context, arg ListRefundPendingBookingsParams) ([]ListRefundPendingBookingsRow, error) {
	rows, err := q.db.Query(ctx, listRefundPendingBookings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefundPendingBookingsRow{}
	for rows.Next() {
		var i ListRefundPendingBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TripID,
			&i.UserID,
			&i.GuestInfo,
			&i.PickupInfo,
			&i.DropoffInfo,
			&i.SeatCodes,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.RefundedAt,
			&i.RefundReference,
			&i.RefundNote,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.OriginName,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTripForBooking = `-- name: LockTripForBooking :one

SELECT id, provider_id, bus_id, origin_id, destination_id, departure_time, arrival_time, base_price, price_modifier, is_hot_deal, pickup_points, dropoff_points, booked_seats, available_seats, status, created_at, version FROM trips WHERE id = $1 FOR UPDATE NOWAIT
`

func (q *Queries) LockTripForBooking(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRow(ctx, lockTripForBooking, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusID,
		&i.OriginID,
		&i.DestinationID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.PriceModifier,
		&i.IsHotDeal,
		&i.PickupPoints,
		&i.DropoffPoints,
		&i.BookedSeats,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const markBookingExpired = `-- name: MarkBookingExpired :one
UPDATE bookings SET
    status = 'expired',
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note
`

func (q *Queries) MarkBookingExpired(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, markBookingExpired, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const markBookingPaid = `-- name: MarkBookingPaid :one
UPDATE bookings SET
    status = 'paid',
    expires_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note
`

func (q *Queries) MarkBookingPaid(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, markBookingPaid, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const markBookingRefundPending = `-- name: MarkBookingRefundPending :one

UPDATE bookings SET
    status = 'refund_pending',
    refunded_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND status IN ('paid', 'pending')
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note
`

func (q *Queries) MarkBookingRefundPending(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, markBookingRefundPending, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const markBookingRefunded = `-- name: MarkBookingRefunded :one

UPDATE bookings SET
    status = 'cancelled',
    refunded_at = NOW(),
    refund_reference = $2,
    refund_note = $3,
    updated_at = NOW()
WHERE id = $1 AND status = 'refund_pending'
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note
`

type MarkBookingRefundedParams struct {
	ID              int64   `json:"id"`
	RefundReference *string `json:"refundReference"`
	RefundNote      *string `json:"refundNote"`
}

func (q *Queries) MarkBookingRefunded(ctx context.Context, arg MarkBookingRefundedParams) (Booking, error) {
	row := q.db.QueryRow(ctx, markBookingRefunded, arg.ID, arg.RefundReference, arg.RefundNote)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const releaseTripSeats = `-- name: ReleaseTripSeats :one
UPDATE trips SET
    booked_seats = ARRAY(SELECT unnest(COALESCE(booked_seats, '{}'::text[])) EXCEPT SELECT unnest($2::text[])),
    available_seats = available_seats + $3,
    version = version + 1
WHERE id = $1
RETURNING id, provider_id, bus_id, origin_id, destination_id, departure_time, arrival_time, base_price, price_modifier, is_hot_deal, pickup_points, dropoff_points, booked_seats, available_seats, status, created_at, version
`

type ReleaseTripSeatsParams struct {
	ID             int64    `json:"id"`
	Column2        []string `json:"column2"`
	AvailableSeats int32    `json:"availableSeats"`
}

func (q *Queries) ReleaseTripSeats(ctx context.Context, arg ReleaseTripSeatsParams) (Trip, error) {
	row := q.db.QueryRow(ctx, releaseTripSeats, arg.ID, arg.Column2, arg.AvailableSeats)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusID,
		&i.OriginID,
		&i.DestinationID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.PriceModifier,
		&i.IsHotDeal,
		&i.PickupPoints,
		&i.DropoffPoints,
		&i.BookedSeats,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const revertBookingToPaid = `-- name: RevertBookingToPaid :one
UPDATE bookings SET
    status = 'paid',
    refunded_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND status = 'refund_pending'
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note
`

func (q *Queries) RevertBookingToPaid(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, revertBookingToPaid, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET 
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, trip_id, user_id, guest_info, pickup_info, dropoff_info, seat_codes, total_amount, status, payment_method, created_at, updated_at, expires_at, refunded_at, refund_reference, refund_note
`

type UpdateBookingStatusParams struct {
	ID     int64   `json:"id"`
	Status *string `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TripID,
		&i.UserID,
		&i.GuestInfo,
		&i.PickupInfo,
		&i.DropoffInfo,
		&i.SeatCodes,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RefundedAt,
		&i.RefundReference,
		&i.RefundNote,
	)
	return i, err
}

const updateTripSeatsAtomic = `-- name: UpdateTripSeatsAtomic :one
UPDATE trips SET
    booked_seats = array_cat(COALESCE(booked_seats, '{}'::text[]), $2::text[]),
    available_seats = available_seats - $3,
    version = version + 1
WHERE id = $1 
  AND version = $4
  AND available_seats >= $3
RETURNING id, provider_id, bus_id, origin_id, destination_id, departure_time, arrival_time, base_price, price_modifier, is_hot_deal, pickup_points, dropoff_points, booked_seats, available_seats, status, created_at, version
`

type UpdateTripSeatsAtomicParams struct {
	ID             int64    `json:"id"`
	Column2        []string `json:"column2"`
	AvailableSeats int32    `json:"availableSeats"`
	Version        *int32   `json:"version"`
}

func (q *Queries) UpdateTripSeatsAtomic(ctx context.Context, arg UpdateTripSeatsAtomicParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripSeatsAtomic,
		arg.ID,
		arg.Column2,
		arg.AvailableSeats,
		arg.Version,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusID,
		&i.OriginID,
		&i.DestinationID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.PriceModifier,
		&i.IsHotDeal,
		&i.PickupPoints,
		&i.DropoffPoints,
		&i.BookedSeats,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}
