// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"context"
)

const busExistsByLicensePlate = `-- name: BusExistsByLicensePlate :one
SELECT EXISTS (
    SELECT 1
    FROM buses
    WHERE license_plate = $1
)
`

func (q *Queries) BusExistsByLicensePlate(ctx context.Context, licensePlate string) (bool, error) {
	row := q.db.QueryRow(ctx, busExistsByLicensePlate, licensePlate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countBuses = `-- name: CountBuses :one
SELECT COUNT(*) FROM buses b
WHERE ($1::text IS NULL OR b.license_plate ILIKE '%' || $1::text || '%')
AND ($2::text IS NULL OR b.status = $2)
AND ($3::int IS NULL OR b.provider_id = $3)
`

type CountBusesParams struct {
	Q          *string `json:"q"`
	Status     *string `json:"status"`
	ProviderID *int32  `json:"providerId"`
}

func (q *Queries) CountBuses(ctx context.Context, arg CountBusesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBuses, arg.Q, arg.Status, arg.ProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBusesByProvider = `-- name: CountBusesByProvider :one
SELECT COUNT(*) FROM buses b
WHERE b.provider_id = $1
AND ($2::text IS NULL OR b.license_plate ILIKE '%' || $2::text || '%')
AND ($3::text IS NULL OR b.status = $3)
`

type CountBusesByProviderParams struct {
	ProviderID int32   `json:"providerId"`
	Q          *string `json:"q"`
	Status     *string `json:"status"`
}

func (q *Queries) CountBusesByProvider(ctx context.Context, arg CountBusesByProviderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBusesByProvider, arg.ProviderID, arg.Q, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBus = `-- name: CreateBus :one
INSERT INTO buses (provider_id, bus_type_id, license_plate, status, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider_id, bus_type_id, license_plate, status, image_url
`

type CreateBusParams struct {
	ProviderID   int32   `json:"providerId"`
	BusTypeID    int32   `json:"busTypeId"`
	LicensePlate string  `json:"licensePlate"`
	Status       *string `json:"status"`
	ImageUrl     *string `json:"imageUrl"`
}

func (q *Queries) CreateBus(ctx context.Context, arg CreateBusParams) (Bus, error) {
	row := q.db.QueryRow(ctx, createBus,
		arg.ProviderID,
		arg.BusTypeID,
		arg.LicensePlate,
		arg.Status,
		arg.ImageUrl,
	)
	var i Bus
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusTypeID,
		&i.LicensePlate,
		&i.Status,
		&i.ImageUrl,
	)
	return i, err
}

const deleteBus = `-- name: DeleteBus :exec
DELETE FROM buses WHERE id = $1
`

func (q *Queries) DeleteBus(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBus, id)
	return err
}

const getBusByID = `-- name: GetBusByID :one
SELECT b.id, b.provider_id, b.bus_type_id, b.license_plate, b.status, b.image_url, bt.name as bus_type_name, bt.total_seats, p.name as provider_name
FROM buses b
JOIN bus_types bt ON b.bus_type_id = bt.id
JOIN providers p ON b.provider_id = p.id
WHERE b.id = $1
`

type GetBusByIDRow struct {
	ID           int32   `json:"id"`
	ProviderID   int32   `json:"providerId"`
	BusTypeID    int32   `json:"busTypeId"`
	LicensePlate string  `json:"licensePlate"`
	Status       *string `json:"status"`
	ImageUrl     *string `json:"imageUrl"`
	BusTypeName  string  `json:"busTypeName"`
	TotalSeats   int32   `json:"totalSeats"`
	ProviderName string  `json:"providerName"`
}

func (q *Queries) GetBusByID(ctx context.Context, id int32) (GetBusByIDRow, error) {
	row := q.db.QueryRow(ctx, getBusByID, id)
	var i GetBusByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusTypeID,
		&i.LicensePlate,
		&i.Status,
		&i.ImageUrl,
		&i.BusTypeName,
		&i.TotalSeats,
		&i.ProviderName,
	)
	return i, err
}

const getBusesByType = `-- name: GetBusesByType :many
SELECT id, provider_id, bus_type_id, license_plate, status, image_url FROM buses WHERE bus_type_id = $1 AND status = 'active'
`

func (q *Queries) GetBusesByType(ctx context.Context, busTypeID int32) ([]Bus, error) {
	rows, err := q.db.Query(ctx, getBusesByType, busTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bus{}
	for rows.Next() {
		var i Bus
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.BusTypeID,
			&i.LicensePlate,
			&i.Status,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuses = `-- name: ListBuses :many
SELECT b.id, b.provider_id, b.bus_type_id, b.license_plate, b.status, b.image_url, bt.name as bus_type_name, bt.total_seats, p.name as provider_name
FROM buses b
JOIN bus_types bt ON b.bus_type_id = bt.id
JOIN providers p ON b.provider_id = p.id
WHERE ($3::text IS NULL OR (
  b.license_plate ILIKE '%' || $3::text || '%'
  OR bt.name ILIKE '%' || $3::text || '%'
  OR p.name ILIKE '%' || $3::text || '%'
))
AND ($4::text IS NULL OR b.status = $4)
AND ($5::int IS NULL OR b.provider_id = $5)
ORDER BY p.name, b.license_plate
LIMIT $1 OFFSET $2
`

type ListBusesParams struct {
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
	Q          *string `json:"q"`
	Status     *string `json:"status"`
	ProviderID *int32  `json:"providerId"`
}

type ListBusesRow struct {
	ID           int32   `json:"id"`
	ProviderID   int32   `json:"providerId"`
	BusTypeID    int32   `json:"busTypeId"`
	LicensePlate string  `json:"licensePlate"`
	Status       *string `json:"status"`
	ImageUrl     *string `json:"imageUrl"`
	BusTypeName  string  `json:"busTypeName"`
	TotalSeats   int32   `json:"totalSeats"`
	ProviderName string  `json:"providerName"`
}

func (q *Queries) ListBuses(ctx context.Context, arg ListBusesParams) ([]ListBusesRow, error) {
	rows, err := q.db.Query(ctx, listBuses,
		arg.Limit,
		arg.Offset,
		arg.Q,
		arg.Status,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusesRow{}
	for rows.Next() {
		var i ListBusesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.BusTypeID,
			&i.LicensePlate,
			&i.Status,
			&i.ImageUrl,
			&i.BusTypeName,
			&i.TotalSeats,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusesByProvider = `-- name: ListBusesByProvider :many
SELECT b.id, b.provider_id, b.bus_type_id, b.license_plate, b.status, b.image_url, bt.name as bus_type_name, bt.total_seats, p.name as provider_name
FROM buses b
JOIN bus_types bt ON b.bus_type_id = bt.id
JOIN providers p ON b.provider_id = p.id
WHERE b.provider_id = $1
AND ($4::text IS NULL OR (
  b.license_plate ILIKE '%' || $4::text || '%'
  OR bt.name ILIKE '%' || $4::text || '%'
  OR p.name ILIKE '%' || $4::text || '%'
))
AND ($5::text IS NULL OR b.status = $5)
ORDER BY b.license_plate
LIMIT $2 OFFSET $3
`

type ListBusesByProviderParams struct {
	ProviderID int32   `json:"providerId"`
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
	Q          *string `json:"q"`
	Status     *string `json:"status"`
}

type ListBusesByProviderRow struct {
	ID           int32   `json:"id"`
	ProviderID   int32   `json:"providerId"`
	BusTypeID    int32   `json:"busTypeId"`
	LicensePlate string  `json:"licensePlate"`
	Status       *string `json:"status"`
	ImageUrl     *string `json:"imageUrl"`
	BusTypeName  string  `json:"busTypeName"`
	TotalSeats   int32   `json:"totalSeats"`
	ProviderName string  `json:"providerName"`
}

func (q *Queries) ListBusesByProvider(ctx context.Context, arg ListBusesByProviderParams) ([]ListBusesByProviderRow, error) {
	rows, err := q.db.Query(ctx, listBusesByProvider,
		arg.ProviderID,
		arg.Limit,
		arg.Offset,
		arg.Q,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusesByProviderRow{}
	for rows.Next() {
		var i ListBusesByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.BusTypeID,
			&i.LicensePlate,
			&i.Status,
			&i.ImageUrl,
			&i.BusTypeName,
			&i.TotalSeats,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBus = `-- name: UpdateBus :one
UPDATE buses SET 
    bus_type_id = COALESCE($2, bus_type_id),
    license_plate = COALESCE($3, license_plate),
    status = COALESCE($4, status),
    image_url = COALESCE($5, image_url)
WHERE id = $1
RETURNING id, provider_id, bus_type_id, license_plate, status, image_url
`

type UpdateBusParams struct {
	ID           int32   `json:"id"`
	BusTypeID    int32   `json:"busTypeId"`
	LicensePlate string  `json:"licensePlate"`
	Status       *string `json:"status"`
	ImageUrl     *string `json:"imageUrl"`
}

func (q *Queries) UpdateBus(ctx context.Context, arg UpdateBusParams) (Bus, error) {
	row := q.db.QueryRow(ctx, updateBus,
		arg.ID,
		arg.BusTypeID,
		arg.LicensePlate,
		arg.Status,
		arg.ImageUrl,
	)
	var i Bus
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusTypeID,
		&i.LicensePlate,
		&i.Status,
		&i.ImageUrl,
	)
	return i, err
}

const updateBusStatus = `-- name: UpdateBusStatus :one
UPDATE buses SET status = $2 WHERE id = $1 RETURNING id, provider_id, bus_type_id, license_plate, status, image_url
`

type UpdateBusStatusParams struct {
	ID     int32   `json:"id"`
	Status *string `json:"status"`
}

func (q *Queries) UpdateBusStatus(ctx context.Context, arg UpdateBusStatusParams) (Bus, error) {
	row := q.db.QueryRow(ctx, updateBusStatus, arg.ID, arg.Status)
	var i Bus
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusTypeID,
		&i.LicensePlate,
		&i.Status,
		&i.ImageUrl,
	)
	return i, err
}
