// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bus_type.sql

package models

import (
	"context"
	"encoding/json"
)

const countBusTypes = `-- name: CountBusTypes :one
SELECT COUNT(*) FROM bus_types
`

func (q *Queries) CountBusTypes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBusTypes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBusType = `-- name: CreateBusType :one
INSERT INTO bus_types (name, total_seats, seat_layout)
VALUES ($1, $2, $3)
RETURNING id, name, total_seats, seat_layout
`

type CreateBusTypeParams struct {
	Name       string          `json:"name"`
	TotalSeats int32           `json:"totalSeats"`
	SeatLayout json.RawMessage `json:"seatLayout"`
}

func (q *Queries) CreateBusType(ctx context.Context, arg CreateBusTypeParams) (BusType, error) {
	row := q.db.QueryRow(ctx, createBusType, arg.Name, arg.TotalSeats, arg.SeatLayout)
	var i BusType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalSeats,
		&i.SeatLayout,
	)
	return i, err
}

const deleteBusType = `-- name: DeleteBusType :exec
DELETE FROM bus_types WHERE id = $1
`

func (q *Queries) DeleteBusType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBusType, id)
	return err
}

const getBusTypeByID = `-- name: GetBusTypeByID :one
SELECT id, name, total_seats, seat_layout FROM bus_types WHERE id = $1
`

func (q *Queries) GetBusTypeByID(ctx context.Context, id int32) (BusType, error) {
	row := q.db.QueryRow(ctx, getBusTypeByID, id)
	var i BusType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalSeats,
		&i.SeatLayout,
	)
	return i, err
}

const listBusTypes = `-- name: ListBusTypes :many
SELECT id, name, total_seats, seat_layout FROM bus_types ORDER BY name LIMIT $1 OFFSET $2
`

type ListBusTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBusTypes(ctx context.Context, arg ListBusTypesParams) ([]BusType, error) {
	rows, err := q.db.Query(ctx, listBusTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusType{}
	for rows.Next() {
		var i BusType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TotalSeats,
			&i.SeatLayout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusTypesPublic = `-- name: ListBusTypesPublic :many
SELECT id, name, total_seats, seat_layout FROM bus_types ORDER BY name
`

func (q *Queries) ListBusTypesPublic(ctx context.Context) ([]BusType, error) {
	rows, err := q.db.Query(ctx, listBusTypesPublic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusType{}
	for rows.Next() {
		var i BusType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TotalSeats,
			&i.SeatLayout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusType = `-- name: UpdateBusType :one
UPDATE bus_types SET 
    name = COALESCE($2, name),
    total_seats = COALESCE($3, total_seats),
    seat_layout = COALESCE($4, seat_layout)
WHERE id = $1
RETURNING id, name, total_seats, seat_layout
`

type UpdateBusTypeParams struct {
	ID         int32           `json:"id"`
	Name       string          `json:"name"`
	TotalSeats int32           `json:"totalSeats"`
	SeatLayout json.RawMessage `json:"seatLayout"`
}

func (q *Queries) UpdateBusType(ctx context.Context, arg UpdateBusTypeParams) (BusType, error) {
	row := q.db.QueryRow(ctx, updateBusType,
		arg.ID,
		arg.Name,
		arg.TotalSeats,
		arg.SeatLayout,
	)
	var i BusType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalSeats,
		&i.SeatLayout,
	)
	return i, err
}
