// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package models

import (
	"context"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, city, address, keywords)
VALUES ($1, $2, $3, $4)
RETURNING id, name, city, address, keywords
`

type CreateLocationParams struct {
	Name     string  `json:"name"`
	City     string  `json:"city"`
	Address  *string `json:"address"`
	Keywords *string `json:"keywords"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Name,
		arg.City,
		arg.Address,
		arg.Keywords,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Keywords,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, name, city, address, keywords FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int32) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Keywords,
	)
	return i, err
}

const listLocationsByCity = `-- name: ListLocationsByCity :many
SELECT id, name, city, address, keywords FROM locations WHERE city = $1 ORDER BY name
`

func (q *Queries) ListLocationsByCity(ctx context.Context, city string) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Keywords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLocations = `-- name: SearchLocations :many
SELECT id, name, city, address, keywords FROM locations 
WHERE city ILIKE '%' || $1 || '%' 
   OR name ILIKE '%' || $1 || '%'
   OR keywords ILIKE '%' || $1 || '%'
ORDER BY city, name
LIMIT 20
`

func (q *Queries) SearchLocations(ctx context.Context, dollar_1 *string) ([]Location, error) {
	rows, err := q.db.Query(ctx, searchLocations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Keywords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
