// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package models

import (
	"context"
)

const countLocations = `-- name: CountLocations :one
SELECT COUNT(*) FROM locations
WHERE ($1::text IS NULL OR (
  name ILIKE '%' || $1::text || '%'
  OR city ILIKE '%' || $1::text || '%'
  OR keywords ILIKE '%' || $1::text || '%'
))
AND ($2::text IS NULL OR city ILIKE '%' || $2::text || '%')
`

type CountLocationsParams struct {
	Q    *string `json:"q"`
	City *string `json:"city"`
}

func (q *Queries) CountLocations(ctx context.Context, arg CountLocationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLocations, arg.Q, arg.City)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, city, address, keywords, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, city, address, keywords, image_url
`

type CreateLocationParams struct {
	Name     string  `json:"name"`
	City     string  `json:"city"`
	Address  *string `json:"address"`
	Keywords *string `json:"keywords"`
	ImageUrl *string `json:"imageUrl"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Name,
		arg.City,
		arg.Address,
		arg.Keywords,
		arg.ImageUrl,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Keywords,
		&i.ImageUrl,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, name, city, address, keywords, image_url FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int32) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Keywords,
		&i.ImageUrl,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, name, city, address, keywords, image_url FROM locations 
WHERE ($3::text IS NULL OR (
  name ILIKE '%' || $3::text || '%'
  OR city ILIKE '%' || $3::text || '%'
  OR keywords ILIKE '%' || $3::text || '%'
))
AND ($4::text IS NULL OR city ILIKE '%' || $4::text || '%')
ORDER BY city, name
LIMIT $1 OFFSET $2
`

type ListLocationsParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Q      *string `json:"q"`
	City   *string `json:"city"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations,
		arg.Limit,
		arg.Offset,
		arg.Q,
		arg.City,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Keywords,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByCity = `-- name: ListLocationsByCity :many
SELECT id, name, city, address, keywords, image_url FROM locations WHERE city = $1 ORDER BY name
`

func (q *Queries) ListLocationsByCity(ctx context.Context, city string) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Keywords,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLocations = `-- name: SearchLocations :many
SELECT id, name, city, address, keywords, image_url FROM locations 
WHERE city ILIKE '%' || $1 || '%'
OR name ILIKE '%' || $1 || '%'
OR keywords ILIKE '%' || $1 || '%'
ORDER BY city, name
LIMIT 20
`

func (q *Queries) SearchLocations(ctx context.Context, dollar_1 *string) ([]Location, error) {
	rows, err := q.db.Query(ctx, searchLocations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Keywords,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations SET 
    name = COALESCE($2, name),
    city = COALESCE($3, city),
    address = COALESCE($4, address),
    keywords = COALESCE($5, keywords),
    image_url = COALESCE($6, image_url)
WHERE id = $1
RETURNING id, name, city, address, keywords, image_url
`

type UpdateLocationParams struct {
	ID       int32   `json:"id"`
	Name     string  `json:"name"`
	City     string  `json:"city"`
	Address  *string `json:"address"`
	Keywords *string `json:"keywords"`
	ImageUrl *string `json:"imageUrl"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Address,
		arg.Keywords,
		arg.ImageUrl,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Keywords,
		&i.ImageUrl,
	)
	return i, err
}
