// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID            int64              `json:"id"`
	Code          string             `json:"code"`
	TripID        int64              `json:"tripId"`
	UserID        *int64             `json:"userId"`
	GuestInfo     json.RawMessage    `json:"guestInfo"`
	PickupInfo    json.RawMessage    `json:"pickupInfo"`
	DropoffInfo   json.RawMessage    `json:"dropoffInfo"`
	SeatCodes     []string           `json:"seatCodes"`
	TotalAmount   pgtype.Numeric     `json:"totalAmount"`
	Status        *string            `json:"status"`
	PaymentMethod *string            `json:"paymentMethod"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	ExpiresAt     pgtype.Timestamptz `json:"expiresAt"`
}

type Bus struct {
	ID           int32   `json:"id"`
	ProviderID   int32   `json:"providerId"`
	BusTypeID    int32   `json:"busTypeId"`
	LicensePlate string  `json:"licensePlate"`
	Status       *string `json:"status"`
	ImageUrl     *string `json:"imageUrl"`
}

type BusType struct {
	ID         int32           `json:"id"`
	Name       string          `json:"name"`
	TotalSeats int32           `json:"totalSeats"`
	SeatLayout json.RawMessage `json:"seatLayout"`
}

type Location struct {
	ID       int32   `json:"id"`
	Name     string  `json:"name"`
	City     string  `json:"city"`
	Address  *string `json:"address"`
	Keywords *string `json:"keywords"`
	ImageUrl *string `json:"imageUrl"`
}

type OutboxEvent struct {
	ID          uuid.UUID          `json:"id"`
	Topic       string             `json:"topic"`
	Payload     json.RawMessage    `json:"payload"`
	Status      *string            `json:"status"`
	RetryCount  *int32             `json:"retryCount"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	ProcessedAt pgtype.Timestamptz `json:"processedAt"`
}

type PaymentTransaction struct {
	ID            uuid.UUID          `json:"id"`
	BookingID     int64              `json:"bookingId"`
	OrderCode     string             `json:"orderCode"`
	Amount        pgtype.Numeric     `json:"amount"`
	Status        *string            `json:"status"`
	PaymentMethod *string            `json:"paymentMethod"`
	WebhookData   []byte             `json:"webhookData"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	PaidAt        pgtype.Timestamptz `json:"paidAt"`
}

type Provider struct {
	ID           int32   `json:"id"`
	Name         string  `json:"name"`
	Hotline      *string `json:"hotline"`
	Slug         *string `json:"slug"`
	PolicyRefund *string `json:"policyRefund"`
	IsActive     *bool   `json:"isActive"`
	ImageUrl     *string `json:"imageUrl"`
}

type Trip struct {
	ID             int64              `json:"id"`
	ProviderID     int32              `json:"providerId"`
	BusID          int32              `json:"busId"`
	OriginID       int32              `json:"originId"`
	DestinationID  int32              `json:"destinationId"`
	DepartureTime  pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime    pgtype.Timestamptz `json:"arrivalTime"`
	BasePrice      pgtype.Numeric     `json:"basePrice"`
	PriceModifier  pgtype.Numeric     `json:"priceModifier"`
	IsHotDeal      *bool              `json:"isHotDeal"`
	PickupPoints   json.RawMessage    `json:"pickupPoints"`
	DropoffPoints  json.RawMessage    `json:"dropoffPoints"`
	BookedSeats    []string           `json:"bookedSeats"`
	AvailableSeats int32              `json:"availableSeats"`
	Status         *string            `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	Version        *int32             `json:"version"`
}

type User struct {
	ID           int64              `json:"id"`
	Phone        string             `json:"phone"`
	PasswordHash string             `json:"passwordHash"`
	FullName     string             `json:"fullName"`
	Email        *string            `json:"email"`
	Role         *string            `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	Username     *string            `json:"username"`
}
