// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox.sql

package models

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (topic, payload)
VALUES ($1, $2)
RETURNING id, topic, payload, status, retry_count, created_at, processed_at
`

type CreateOutboxEventParams struct {
	Topic   string          `json:"topic"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.Topic, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, topic, payload, status, retry_count, created_at, processed_at FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events SET 
    status = 'failed',
    retry_count = retry_count + 1
WHERE id = $1
`

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, id)
	return err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events SET 
    status = 'processed',
    processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}
