// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (booking_id, order_code, amount, payment_method)
VALUES ($1, $2, $3, $4)
RETURNING id, booking_id, order_code, amount, status, payment_method, webhook_data, created_at, paid_at
`

type CreatePaymentTransactionParams struct {
	BookingID     int64          `json:"bookingId"`
	OrderCode     string         `json:"orderCode"`
	Amount        pgtype.Numeric `json:"amount"`
	PaymentMethod *string        `json:"paymentMethod"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, createPaymentTransaction,
		arg.BookingID,
		arg.OrderCode,
		arg.Amount,
		arg.PaymentMethod,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderCode,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.WebhookData,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getPaymentByOrderCode = `-- name: GetPaymentByOrderCode :one
SELECT id, booking_id, order_code, amount, status, payment_method, webhook_data, created_at, paid_at FROM payment_transactions WHERE order_code = $1
`

func (q *Queries) GetPaymentByOrderCode(ctx context.Context, orderCode string) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderCode, orderCode)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderCode,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.WebhookData,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getPaymentsByBookingID = `-- name: GetPaymentsByBookingID :many
SELECT id, booking_id, order_code, amount, status, payment_method, webhook_data, created_at, paid_at FROM payment_transactions WHERE booking_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetPaymentsByBookingID(ctx context.Context, bookingID int64) ([]PaymentTransaction, error) {
	rows, err := q.db.Query(ctx, getPaymentsByBookingID, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentTransaction{}
	for rows.Next() {
		var i PaymentTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.OrderCode,
			&i.Amount,
			&i.Status,
			&i.PaymentMethod,
			&i.WebhookData,
			&i.CreatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentFailed = `-- name: UpdatePaymentFailed :one
UPDATE payment_transactions SET
    status = 'failed',
    webhook_data = $2
WHERE order_code = $1 AND status = 'pending'
RETURNING id, booking_id, order_code, amount, status, payment_method, webhook_data, created_at, paid_at
`

type UpdatePaymentFailedParams struct {
	OrderCode   string `json:"orderCode"`
	WebhookData []byte `json:"webhookData"`
}

func (q *Queries) UpdatePaymentFailed(ctx context.Context, arg UpdatePaymentFailedParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, updatePaymentFailed, arg.OrderCode, arg.WebhookData)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderCode,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.WebhookData,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const updatePaymentSuccess = `-- name: UpdatePaymentSuccess :one
UPDATE payment_transactions SET
    status = 'success',
    webhook_data = $2,
    paid_at = NOW()
WHERE order_code = $1 AND status = 'pending'
RETURNING id, booking_id, order_code, amount, status, payment_method, webhook_data, created_at, paid_at
`

type UpdatePaymentSuccessParams struct {
	OrderCode   string `json:"orderCode"`
	WebhookData []byte `json:"webhookData"`
}

func (q *Queries) UpdatePaymentSuccess(ctx context.Context, arg UpdatePaymentSuccessParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, updatePaymentSuccess, arg.OrderCode, arg.WebhookData)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderCode,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.WebhookData,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}
