// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"context"
)

const countProviders = `-- name: CountProviders :one
SELECT COUNT(*) FROM providers
WHERE ($1::text IS NULL OR (
  name ILIKE '%' || $1::text || '%'
  OR hotline ILIKE '%' || $1::text || '%'
  OR slug ILIKE '%' || $1::text || '%'
))
AND ($2::boolean IS NULL OR is_active = $2)
`

type CountProvidersParams struct {
	Q        *string `json:"q"`
	IsActive *bool   `json:"isActive"`
}

func (q *Queries) CountProviders(ctx context.Context, arg CountProvidersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviders, arg.Q, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (name, hotline, slug, policy_refund)
VALUES ($1, $2, $3, $4)
RETURNING id, name, hotline, slug, policy_refund, is_active, image_url
`

type CreateProviderParams struct {
	Name         string  `json:"name"`
	Hotline      *string `json:"hotline"`
	Slug         *string `json:"slug"`
	PolicyRefund *string `json:"policyRefund"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Hotline,
		arg.Slug,
		arg.PolicyRefund,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hotline,
		&i.Slug,
		&i.PolicyRefund,
		&i.IsActive,
		&i.ImageUrl,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, hotline, slug, policy_refund, is_active, image_url FROM providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id int32) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hotline,
		&i.Slug,
		&i.PolicyRefund,
		&i.IsActive,
		&i.ImageUrl,
	)
	return i, err
}

const getProviderBySlug = `-- name: GetProviderBySlug :one
SELECT id, name, hotline, slug, policy_refund, is_active, image_url FROM providers WHERE slug = $1
`

func (q *Queries) GetProviderBySlug(ctx context.Context, slug *string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderBySlug, slug)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hotline,
		&i.Slug,
		&i.PolicyRefund,
		&i.IsActive,
		&i.ImageUrl,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, hotline, slug, policy_refund, is_active, image_url FROM providers WHERE is_active = true ORDER BY name
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hotline,
			&i.Slug,
			&i.PolicyRefund,
			&i.IsActive,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersAdmin = `-- name: ListProvidersAdmin :many
SELECT id, name, hotline, slug, policy_refund, is_active, image_url FROM providers
WHERE ($3::text IS NULL OR (
  name ILIKE '%' || $3::text || '%'
  OR hotline ILIKE '%' || $3::text || '%'
  OR slug ILIKE '%' || $3::text || '%'
))
AND ($4::boolean IS NULL OR is_active = $4)
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListProvidersAdminParams struct {
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
	Q        *string `json:"q"`
	IsActive *bool   `json:"isActive"`
}

func (q *Queries) ListProvidersAdmin(ctx context.Context, arg ListProvidersAdminParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersAdmin,
		arg.Limit,
		arg.Offset,
		arg.Q,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hotline,
			&i.Slug,
			&i.PolicyRefund,
			&i.IsActive,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleProviderActive = `-- name: ToggleProviderActive :one
UPDATE providers SET is_active = NOT is_active WHERE id = $1 RETURNING id, name, hotline, slug, policy_refund, is_active, image_url
`

func (q *Queries) ToggleProviderActive(ctx context.Context, id int32) (Provider, error) {
	row := q.db.QueryRow(ctx, toggleProviderActive, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hotline,
		&i.Slug,
		&i.PolicyRefund,
		&i.IsActive,
		&i.ImageUrl,
	)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers SET 
    name = COALESCE($2, name),
    hotline = COALESCE($3, hotline),
    slug = COALESCE($4, slug),
    policy_refund = COALESCE($5, policy_refund)
WHERE id = $1
RETURNING id, name, hotline, slug, policy_refund, is_active, image_url
`

type UpdateProviderParams struct {
	ID           int32   `json:"id"`
	Name         string  `json:"name"`
	Hotline      *string `json:"hotline"`
	Slug         *string `json:"slug"`
	PolicyRefund *string `json:"policyRefund"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.Hotline,
		arg.Slug,
		arg.PolicyRefund,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hotline,
		&i.Slug,
		&i.PolicyRefund,
		&i.IsActive,
		&i.ImageUrl,
	)
	return i, err
}
