// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider.sql

package models

import (
	"context"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (name, hotline, slug, policy_refund)
VALUES ($1, $2, $3, $4)
RETURNING id, name, hotline, slug, policy_refund, is_active
`

type CreateProviderParams struct {
	Name         string  `json:"name"`
	Hotline      *string `json:"hotline"`
	Slug         *string `json:"slug"`
	PolicyRefund *string `json:"policyRefund"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Hotline,
		arg.Slug,
		arg.PolicyRefund,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hotline,
		&i.Slug,
		&i.PolicyRefund,
		&i.IsActive,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, hotline, slug, policy_refund, is_active FROM providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id int32) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hotline,
		&i.Slug,
		&i.PolicyRefund,
		&i.IsActive,
	)
	return i, err
}

const getProviderBySlug = `-- name: GetProviderBySlug :one
SELECT id, name, hotline, slug, policy_refund, is_active FROM providers WHERE slug = $1
`

func (q *Queries) GetProviderBySlug(ctx context.Context, slug *string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderBySlug, slug)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hotline,
		&i.Slug,
		&i.PolicyRefund,
		&i.IsActive,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, hotline, slug, policy_refund, is_active FROM providers WHERE is_active = true ORDER BY name
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hotline,
			&i.Slug,
			&i.PolicyRefund,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
