// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BrowseUpcomingTrips(ctx context.Context, arg BrowseUpcomingTripsParams) ([]BrowseUpcomingTripsRow, error)
	BusExistsByLicensePlate(ctx context.Context, licensePlate string) (bool, error)
	CountActiveBookingsByTripID(ctx context.Context, tripID int64) (int64, error)
	CountBookingsByTrip(ctx context.Context, tripID int64) (int64, error)
	CountBrowseUpcomingTrips(ctx context.Context, arg CountBrowseUpcomingTripsParams) (int64, error)
	CountBusTypes(ctx context.Context) (int64, error)
	CountBuses(ctx context.Context) (int64, error)
	CountBusesByProvider(ctx context.Context, providerID int32) (int64, error)
	CountLocations(ctx context.Context) (int64, error)
	CountProviders(ctx context.Context) (int64, error)
	CountSearchTrips(ctx context.Context, arg CountSearchTripsParams) (int64, error)
	CountTripsAdmin(ctx context.Context, arg CountTripsAdminParams) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateBookingWithExpiry(ctx context.Context, arg CreateBookingWithExpiryParams) (Booking, error)
	CreateBus(ctx context.Context, arg CreateBusParams) (Bus, error)
	CreateBusType(ctx context.Context, arg CreateBusTypeParams) (BusType, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBus(ctx context.Context, id int32) error
	DeleteBusType(ctx context.Context, id int32) error
	DeleteLocation(ctx context.Context, id int32) error
	DeleteProvider(ctx context.Context, id int32) error
	DeleteTrip(ctx context.Context, id int64) error
	GetBookingByCode(ctx context.Context, code string) (Booking, error)
	GetBookingByID(ctx context.Context, id int64) (Booking, error)
	// ============================================================================
	// PAYMENT FLOW QUERIES
	// ============================================================================
	// Lock booking row for payment processing (prevent double-pay)
	GetBookingForPayment(ctx context.Context, id int64) (Booking, error)
	GetBusByID(ctx context.Context, id int32) (GetBusByIDRow, error)
	GetBusTypeByID(ctx context.Context, id int32) (BusType, error)
	GetBusesByType(ctx context.Context, busTypeID int32) ([]Bus, error)
	// FOR UPDATE SKIP LOCKED: safe concurrent processing without deadlock
	GetExpiredPendingBookings(ctx context.Context, limit int32) ([]Booking, error)
	GetLocationByID(ctx context.Context, id int32) (Location, error)
	GetPaymentByOrderCode(ctx context.Context, orderCode string) (PaymentTransaction, error)
	GetPaymentsByBookingID(ctx context.Context, bookingID int64) ([]PaymentTransaction, error)
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	GetProviderByID(ctx context.Context, id int32) (Provider, error)
	GetProviderBySlug(ctx context.Context, slug *string) (Provider, error)
	GetTripByID(ctx context.Context, id int64) (GetTripByIDRow, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByIdentifier(ctx context.Context, phone string) (User, error)
	GetUserByIdentity(ctx context.Context, phone string) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]ListBookingsByUserRow, error)
	ListBusTypes(ctx context.Context, arg ListBusTypesParams) ([]BusType, error)
	ListBusTypesPublic(ctx context.Context) ([]BusType, error)
	ListBuses(ctx context.Context, arg ListBusesParams) ([]ListBusesRow, error)
	ListBusesByProvider(ctx context.Context, arg ListBusesByProviderParams) ([]ListBusesByProviderRow, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error)
	ListLocationsByCity(ctx context.Context, city string) ([]Location, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListProvidersAdmin(ctx context.Context, arg ListProvidersAdminParams) ([]Provider, error)
	ListTripsAdmin(ctx context.Context, arg ListTripsAdminParams) ([]ListTripsAdminRow, error)
	// ============================================================================
	// BOOKING LOCKING QUERIES - For race condition handling
	// ============================================================================
	// Lock trip row for atomic seat update (NOWAIT = fail fast if locked)
	LockTripForBooking(ctx context.Context, id int64) (Trip, error)
	MarkBookingExpired(ctx context.Context, id int64) (Booking, error)
	MarkBookingPaid(ctx context.Context, id int64) (Booking, error)
	MarkOutboxEventFailed(ctx context.Context, id uuid.UUID) error
	MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error
	// Release seats when booking cancelled/expired (using array subtraction)
	ReleaseTripSeats(ctx context.Context, arg ReleaseTripSeatsParams) (Trip, error)
	SearchLocations(ctx context.Context, dollar_1 *string) ([]Location, error)
	SearchTrips(ctx context.Context, arg SearchTripsParams) ([]SearchTripsRow, error)
	ToggleProviderActive(ctx context.Context, id int32) (Provider, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdateBus(ctx context.Context, arg UpdateBusParams) (Bus, error)
	UpdateBusStatus(ctx context.Context, arg UpdateBusStatusParams) (Bus, error)
	UpdateBusType(ctx context.Context, arg UpdateBusTypeParams) (BusType, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdatePaymentFailed(ctx context.Context, arg UpdatePaymentFailedParams) (PaymentTransaction, error)
	UpdatePaymentSuccess(ctx context.Context, arg UpdatePaymentSuccessParams) (PaymentTransaction, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error)
	UpdateTripSeats(ctx context.Context, arg UpdateTripSeatsParams) (Trip, error)
	// Optimistic locking: only update if version matches and seats available
	UpdateTripSeatsAtomic(ctx context.Context, arg UpdateTripSeatsAtomicParams) (Trip, error)
	UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
