// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountSearchTrips(ctx context.Context, arg CountSearchTripsParams) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBookingByCode(ctx context.Context, code string) (Booking, error)
	GetBookingByID(ctx context.Context, id int64) (Booking, error)
	GetLocationByID(ctx context.Context, id int32) (Location, error)
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	GetProviderByID(ctx context.Context, id int32) (Provider, error)
	GetProviderBySlug(ctx context.Context, slug *string) (Provider, error)
	GetTripByID(ctx context.Context, id int64) (Trip, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByIdentifier(ctx context.Context, phone string) (User, error)
	GetUserByIdentity(ctx context.Context, phone string) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]ListBookingsByUserRow, error)
	ListLocationsByCity(ctx context.Context, city string) ([]Location, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	MarkOutboxEventFailed(ctx context.Context, id uuid.UUID) error
	MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error
	SearchLocations(ctx context.Context, dollar_1 *string) ([]Location, error)
	SearchTrips(ctx context.Context, arg SearchTripsParams) ([]SearchTripsRow, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdateTripSeats(ctx context.Context, arg UpdateTripSeatsParams) (Trip, error)
	UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
