// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trip.sql

package models

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveBookingsByTripID = `-- name: CountActiveBookingsByTripID :one
SELECT COUNT(*) FROM bookings
WHERE trip_id = $1
  AND status IN ('pending', 'paid')
`

func (q *Queries) CountActiveBookingsByTripID(ctx context.Context, tripID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBookingsByTripID, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchTrips = `-- name: CountSearchTrips :one
SELECT COUNT(*) FROM trips
WHERE origin_id = $1
  AND destination_id = $2
  AND DATE(departure_time) = $3::date
  AND available_seats >= $4
  AND status = 'scheduled'
`

type CountSearchTripsParams struct {
	OriginID       int32       `json:"originId"`
	DestinationID  int32       `json:"destinationId"`
	Column3        pgtype.Date `json:"column3"`
	AvailableSeats int32       `json:"availableSeats"`
}

func (q *Queries) CountSearchTrips(ctx context.Context, arg CountSearchTripsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchTrips,
		arg.OriginID,
		arg.DestinationID,
		arg.Column3,
		arg.AvailableSeats,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTripsAdmin = `-- name: CountTripsAdmin :one
SELECT COUNT(*) FROM trips
WHERE ($1::int IS NULL OR provider_id = $1)
  AND ($2::text IS NULL OR status = $2)
`

type CountTripsAdminParams struct {
	ProviderID *int32  `json:"providerId"`
	Status     *string `json:"status"`
}

func (q *Queries) CountTripsAdmin(ctx context.Context, arg CountTripsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTripsAdmin, arg.ProviderID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
    provider_id, bus_id, origin_id, destination_id,
    departure_time, arrival_time, base_price, price_modifier,
    is_hot_deal, pickup_points, dropoff_points, available_seats
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, provider_id, bus_id, origin_id, destination_id, departure_time, arrival_time, base_price, price_modifier, is_hot_deal, pickup_points, dropoff_points, booked_seats, available_seats, status, created_at, version
`

type CreateTripParams struct {
	ProviderID     int32              `json:"providerId"`
	BusID          int32              `json:"busId"`
	OriginID       int32              `json:"originId"`
	DestinationID  int32              `json:"destinationId"`
	DepartureTime  pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime    pgtype.Timestamptz `json:"arrivalTime"`
	BasePrice      pgtype.Numeric     `json:"basePrice"`
	PriceModifier  pgtype.Numeric     `json:"priceModifier"`
	IsHotDeal      *bool              `json:"isHotDeal"`
	PickupPoints   json.RawMessage    `json:"pickupPoints"`
	DropoffPoints  json.RawMessage    `json:"dropoffPoints"`
	AvailableSeats int32              `json:"availableSeats"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.ProviderID,
		arg.BusID,
		arg.OriginID,
		arg.DestinationID,
		arg.DepartureTime,
		arg.ArrivalTime,
		arg.BasePrice,
		arg.PriceModifier,
		arg.IsHotDeal,
		arg.PickupPoints,
		arg.DropoffPoints,
		arg.AvailableSeats,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusID,
		&i.OriginID,
		&i.DestinationID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.PriceModifier,
		&i.IsHotDeal,
		&i.PickupPoints,
		&i.DropoffPoints,
		&i.BookedSeats,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips WHERE id = $1
`

func (q *Queries) DeleteTrip(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTrip, id)
	return err
}

const getTripByID = `-- name: GetTripByID :one
SELECT t.id, t.provider_id, t.bus_id, t.origin_id, t.destination_id, t.departure_time, t.arrival_time, t.base_price, t.price_modifier, t.is_hot_deal, t.pickup_points, t.dropoff_points, t.booked_seats, t.available_seats, t.status, t.created_at, t.version,
       p.name as provider_name,
       o.name as origin_name, o.city as origin_city,
       d.name as destination_name, d.city as destination_city
FROM trips t
JOIN providers p ON t.provider_id = p.id
JOIN locations o ON t.origin_id = o.id
JOIN locations d ON t.destination_id = d.id
WHERE t.id = $1
`

type GetTripByIDRow struct {
	ID              int64              `json:"id"`
	ProviderID      int32              `json:"providerId"`
	BusID           int32              `json:"busId"`
	OriginID        int32              `json:"originId"`
	DestinationID   int32              `json:"destinationId"`
	DepartureTime   pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime     pgtype.Timestamptz `json:"arrivalTime"`
	BasePrice       pgtype.Numeric     `json:"basePrice"`
	PriceModifier   pgtype.Numeric     `json:"priceModifier"`
	IsHotDeal       *bool              `json:"isHotDeal"`
	PickupPoints    json.RawMessage    `json:"pickupPoints"`
	DropoffPoints   json.RawMessage    `json:"dropoffPoints"`
	BookedSeats     []string           `json:"bookedSeats"`
	AvailableSeats  int32              `json:"availableSeats"`
	Status          *string            `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	Version         *int32             `json:"version"`
	ProviderName    string             `json:"providerName"`
	OriginName      string             `json:"originName"`
	OriginCity      string             `json:"originCity"`
	DestinationName string             `json:"destinationName"`
	DestinationCity string             `json:"destinationCity"`
}

func (q *Queries) GetTripByID(ctx context.Context, id int64) (GetTripByIDRow, error) {
	row := q.db.QueryRow(ctx, getTripByID, id)
	var i GetTripByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusID,
		&i.OriginID,
		&i.DestinationID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.PriceModifier,
		&i.IsHotDeal,
		&i.PickupPoints,
		&i.DropoffPoints,
		&i.BookedSeats,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
		&i.ProviderName,
		&i.OriginName,
		&i.OriginCity,
		&i.DestinationName,
		&i.DestinationCity,
	)
	return i, err
}

const listTripsAdmin = `-- name: ListTripsAdmin :many
SELECT t.id, t.provider_id, t.bus_id, t.origin_id, t.destination_id, t.departure_time, t.arrival_time, t.base_price, t.price_modifier, t.is_hot_deal, t.pickup_points, t.dropoff_points, t.booked_seats, t.available_seats, t.status, t.created_at, t.version, 
       p.name as provider_name,
       o.name as origin_name, o.city as origin_city,
       d.name as destination_name, d.city as destination_city
FROM trips t
JOIN providers p ON t.provider_id = p.id
JOIN locations o ON t.origin_id = o.id
JOIN locations d ON t.destination_id = d.id
WHERE ($3::int IS NULL OR t.provider_id = $3)
  AND ($4::text IS NULL OR t.status = $4)
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListTripsAdminParams struct {
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
	ProviderID *int32  `json:"providerId"`
	Status     *string `json:"status"`
}

type ListTripsAdminRow struct {
	ID              int64              `json:"id"`
	ProviderID      int32              `json:"providerId"`
	BusID           int32              `json:"busId"`
	OriginID        int32              `json:"originId"`
	DestinationID   int32              `json:"destinationId"`
	DepartureTime   pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime     pgtype.Timestamptz `json:"arrivalTime"`
	BasePrice       pgtype.Numeric     `json:"basePrice"`
	PriceModifier   pgtype.Numeric     `json:"priceModifier"`
	IsHotDeal       *bool              `json:"isHotDeal"`
	PickupPoints    json.RawMessage    `json:"pickupPoints"`
	DropoffPoints   json.RawMessage    `json:"dropoffPoints"`
	BookedSeats     []string           `json:"bookedSeats"`
	AvailableSeats  int32              `json:"availableSeats"`
	Status          *string            `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	Version         *int32             `json:"version"`
	ProviderName    string             `json:"providerName"`
	OriginName      string             `json:"originName"`
	OriginCity      string             `json:"originCity"`
	DestinationName string             `json:"destinationName"`
	DestinationCity string             `json:"destinationCity"`
}

func (q *Queries) ListTripsAdmin(ctx context.Context, arg ListTripsAdminParams) ([]ListTripsAdminRow, error) {
	rows, err := q.db.Query(ctx, listTripsAdmin,
		arg.Limit,
		arg.Offset,
		arg.ProviderID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripsAdminRow{}
	for rows.Next() {
		var i ListTripsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.BusID,
			&i.OriginID,
			&i.DestinationID,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.BasePrice,
			&i.PriceModifier,
			&i.IsHotDeal,
			&i.PickupPoints,
			&i.DropoffPoints,
			&i.BookedSeats,
			&i.AvailableSeats,
			&i.Status,
			&i.CreatedAt,
			&i.Version,
			&i.ProviderName,
			&i.OriginName,
			&i.OriginCity,
			&i.DestinationName,
			&i.DestinationCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTrips = `-- name: SearchTrips :many
SELECT t.id, t.provider_id, t.bus_id, t.origin_id, t.destination_id, t.departure_time, t.arrival_time, t.base_price, t.price_modifier, t.is_hot_deal, t.pickup_points, t.dropoff_points, t.booked_seats, t.available_seats, t.status, t.created_at, t.version, 
       p.name as provider_name,
       o.name as origin_name, o.city as origin_city,
       d.name as destination_name, d.city as destination_city
FROM trips t
JOIN providers p ON t.provider_id = p.id
JOIN locations o ON t.origin_id = o.id
JOIN locations d ON t.destination_id = d.id
WHERE t.origin_id = $1
  AND t.destination_id = $2
  AND DATE(t.departure_time) = $3::date
  AND t.available_seats >= $4
  AND t.status = 'scheduled'
ORDER BY t.departure_time
LIMIT $5 OFFSET $6
`

type SearchTripsParams struct {
	OriginID       int32       `json:"originId"`
	DestinationID  int32       `json:"destinationId"`
	Column3        pgtype.Date `json:"column3"`
	AvailableSeats int32       `json:"availableSeats"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type SearchTripsRow struct {
	ID              int64              `json:"id"`
	ProviderID      int32              `json:"providerId"`
	BusID           int32              `json:"busId"`
	OriginID        int32              `json:"originId"`
	DestinationID   int32              `json:"destinationId"`
	DepartureTime   pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime     pgtype.Timestamptz `json:"arrivalTime"`
	BasePrice       pgtype.Numeric     `json:"basePrice"`
	PriceModifier   pgtype.Numeric     `json:"priceModifier"`
	IsHotDeal       *bool              `json:"isHotDeal"`
	PickupPoints    json.RawMessage    `json:"pickupPoints"`
	DropoffPoints   json.RawMessage    `json:"dropoffPoints"`
	BookedSeats     []string           `json:"bookedSeats"`
	AvailableSeats  int32              `json:"availableSeats"`
	Status          *string            `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	Version         *int32             `json:"version"`
	ProviderName    string             `json:"providerName"`
	OriginName      string             `json:"originName"`
	OriginCity      string             `json:"originCity"`
	DestinationName string             `json:"destinationName"`
	DestinationCity string             `json:"destinationCity"`
}

func (q *Queries) SearchTrips(ctx context.Context, arg SearchTripsParams) ([]SearchTripsRow, error) {
	rows, err := q.db.Query(ctx, searchTrips,
		arg.OriginID,
		arg.DestinationID,
		arg.Column3,
		arg.AvailableSeats,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTripsRow{}
	for rows.Next() {
		var i SearchTripsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.BusID,
			&i.OriginID,
			&i.DestinationID,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.BasePrice,
			&i.PriceModifier,
			&i.IsHotDeal,
			&i.PickupPoints,
			&i.DropoffPoints,
			&i.BookedSeats,
			&i.AvailableSeats,
			&i.Status,
			&i.CreatedAt,
			&i.Version,
			&i.ProviderName,
			&i.OriginName,
			&i.OriginCity,
			&i.DestinationName,
			&i.DestinationCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips SET
    departure_time = COALESCE($2, departure_time),
    arrival_time = COALESCE($3, arrival_time),
    base_price = COALESCE($4, base_price),
    price_modifier = COALESCE($5, price_modifier),
    is_hot_deal = COALESCE($6, is_hot_deal),
    pickup_points = COALESCE($7, pickup_points),
    dropoff_points = COALESCE($8, dropoff_points),
    available_seats = COALESCE($9, available_seats)
WHERE id = $1
RETURNING id, provider_id, bus_id, origin_id, destination_id, departure_time, arrival_time, base_price, price_modifier, is_hot_deal, pickup_points, dropoff_points, booked_seats, available_seats, status, created_at, version
`

type UpdateTripParams struct {
	ID             int64              `json:"id"`
	DepartureTime  pgtype.Timestamptz `json:"departureTime"`
	ArrivalTime    pgtype.Timestamptz `json:"arrivalTime"`
	BasePrice      pgtype.Numeric     `json:"basePrice"`
	PriceModifier  pgtype.Numeric     `json:"priceModifier"`
	IsHotDeal      *bool              `json:"isHotDeal"`
	PickupPoints   json.RawMessage    `json:"pickupPoints"`
	DropoffPoints  json.RawMessage    `json:"dropoffPoints"`
	AvailableSeats int32              `json:"availableSeats"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.ID,
		arg.DepartureTime,
		arg.ArrivalTime,
		arg.BasePrice,
		arg.PriceModifier,
		arg.IsHotDeal,
		arg.PickupPoints,
		arg.DropoffPoints,
		arg.AvailableSeats,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusID,
		&i.OriginID,
		&i.DestinationID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.PriceModifier,
		&i.IsHotDeal,
		&i.PickupPoints,
		&i.DropoffPoints,
		&i.BookedSeats,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const updateTripSeats = `-- name: UpdateTripSeats :one
UPDATE trips SET
    booked_seats = $2,
    available_seats = $3
WHERE id = $1
RETURNING id, provider_id, bus_id, origin_id, destination_id, departure_time, arrival_time, base_price, price_modifier, is_hot_deal, pickup_points, dropoff_points, booked_seats, available_seats, status, created_at, version
`

type UpdateTripSeatsParams struct {
	ID             int64    `json:"id"`
	BookedSeats    []string `json:"bookedSeats"`
	AvailableSeats int32    `json:"availableSeats"`
}

func (q *Queries) UpdateTripSeats(ctx context.Context, arg UpdateTripSeatsParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripSeats, arg.ID, arg.BookedSeats, arg.AvailableSeats)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusID,
		&i.OriginID,
		&i.DestinationID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.PriceModifier,
		&i.IsHotDeal,
		&i.PickupPoints,
		&i.DropoffPoints,
		&i.BookedSeats,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const updateTripStatus = `-- name: UpdateTripStatus :one
UPDATE trips SET status = $2 WHERE id = $1 RETURNING id, provider_id, bus_id, origin_id, destination_id, departure_time, arrival_time, base_price, price_modifier, is_hot_deal, pickup_points, dropoff_points, booked_seats, available_seats, status, created_at, version
`

type UpdateTripStatusParams struct {
	ID     int64   `json:"id"`
	Status *string `json:"status"`
}

func (q *Queries) UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripStatus, arg.ID, arg.Status)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.BusID,
		&i.OriginID,
		&i.DestinationID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.BasePrice,
		&i.PriceModifier,
		&i.IsHotDeal,
		&i.PickupPoints,
		&i.DropoffPoints,
		&i.BookedSeats,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}
