// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package models

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, password_hash, full_name, email, role, username)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, phone, password_hash, full_name, email, role, created_at, username
`

type CreateUserParams struct {
	Phone        string  `json:"phone"`
	PasswordHash string  `json:"passwordHash"`
	FullName     string  `json:"fullName"`
	Email        *string `json:"email"`
	Role         *string `json:"role"`
	Username     *string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.PasswordHash,
		arg.FullName,
		arg.Email,
		arg.Role,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone, password_hash, full_name, email, role, created_at, username FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, password_hash, full_name, email, role, created_at, username FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByIdentifier = `-- name: GetUserByIdentifier :one
SELECT id, phone, password_hash, full_name, email, role, created_at, username FROM users
WHERE phone = $1 OR email = $1 OR username = $1
`

func (q *Queries) GetUserByIdentifier(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentifier, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT id, phone, password_hash, full_name, email, role, created_at, username FROM users WHERE phone = $1 OR email = $1 OR username = $1
`

func (q *Queries) GetUserByIdentity(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password_hash, full_name, email, role, created_at, username FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, phone, password_hash, full_name, email, role, created_at, username FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    full_name = COALESCE($2, full_name),
    email = COALESCE($3, email),
    username = COALESCE($4, username)
WHERE id = $1
RETURNING id, phone, password_hash, full_name, email, role, created_at, username
`

type UpdateUserParams struct {
	ID       int64   `json:"id"`
	FullName *string `json:"fullName"`
	Email    *string `json:"email"`
	Username *string `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}
