/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminTripsIndexRouteImport } from './routes/admin/trips/index'
import { Route as AdminProvidersIndexRouteImport } from './routes/admin/providers/index'
import { Route as AdminLocationsIndexRouteImport } from './routes/admin/locations/index'
import { Route as AdminBusesIndexRouteImport } from './routes/admin/buses/index'
import { Route as AdminBusTypesIndexRouteImport } from './routes/admin/bus-types/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminTripsIndexRoute = AdminTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersIndexRoute = AdminProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsIndexRoute = AdminLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesIndexRoute = AdminBusesIndexRouteImport.update({
  id: '/buses/',
  path: '/buses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusTypesIndexRoute = AdminBusTypesIndexRouteImport.update({
  id: '/bus-types/',
  path: '/bus-types/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/': typeof PublicIndexRoute
  '/admin/bus-types': typeof AdminBusTypesIndexRoute
  '/admin/buses': typeof AdminBusesIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
  '/admin/providers': typeof AdminProvidersIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/': typeof PublicIndexRoute
  '/admin/bus-types': typeof AdminBusTypesIndexRoute
  '/admin/buses': typeof AdminBusesIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
  '/admin/providers': typeof AdminProvidersIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/bus-types/': typeof AdminBusTypesIndexRoute
  '/admin/buses/': typeof AdminBusesIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
  '/admin/providers/': typeof AdminProvidersIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/'
    | '/admin/bus-types'
    | '/admin/buses'
    | '/admin/locations'
    | '/admin/providers'
    | '/admin/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/'
    | '/admin/bus-types'
    | '/admin/buses'
    | '/admin/locations'
    | '/admin/providers'
    | '/admin/trips'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/admin'
    | '/_auth/login'
    | '/_auth/register'
    | '/admin/dashboard'
    | '/_public/'
    | '/admin/bus-types/'
    | '/admin/buses/'
    | '/admin/locations/'
    | '/admin/providers/'
    | '/admin/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/trips/': {
      id: '/admin/trips/'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers/': {
      id: '/admin/providers/'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations/': {
      id: '/admin/locations/'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses/': {
      id: '/admin/buses/'
      path: '/buses'
      fullPath: '/admin/buses'
      preLoaderRoute: typeof AdminBusesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bus-types/': {
      id: '/admin/bus-types/'
      path: '/bus-types'
      fullPath: '/admin/bus-types'
      preLoaderRoute: typeof AdminBusTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminBusTypesIndexRoute: typeof AdminBusTypesIndexRoute
  AdminBusesIndexRoute: typeof AdminBusesIndexRoute
  AdminLocationsIndexRoute: typeof AdminLocationsIndexRoute
  AdminProvidersIndexRoute: typeof AdminProvidersIndexRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminBusTypesIndexRoute: AdminBusTypesIndexRoute,
  AdminBusesIndexRoute: AdminBusesIndexRoute,
  AdminLocationsIndexRoute: AdminLocationsIndexRoute,
  AdminProvidersIndexRoute: AdminProvidersIndexRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
