/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as PublicVoiceBookingRouteImport } from './routes/_public/voice-booking'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicMyBookingsRouteImport } from './routes/_public/my-bookings'
import { Route as PublicChatRouteImport } from './routes/_public/chat'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTripsIndexRouteImport } from './routes/admin/trips/index'
import { Route as AdminRefundRequestsIndexRouteImport } from './routes/admin/refund-requests/index'
import { Route as AdminProvidersIndexRouteImport } from './routes/admin/providers/index'
import { Route as AdminLocationsIndexRouteImport } from './routes/admin/locations/index'
import { Route as AdminBusesIndexRouteImport } from './routes/admin/buses/index'
import { Route as AdminBusTypesIndexRouteImport } from './routes/admin/bus-types/index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings/index'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin/bookings.$bookingId'
import { Route as PublicTripsTripIdRouteImport } from './routes/_public/trips.$tripId'
import { Route as PublicPaymentBookingCodeRouteImport } from './routes/_public/payment.$bookingCode'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const PublicVoiceBookingRoute = PublicVoiceBookingRouteImport.update({
  id: '/voice-booking',
  path: '/voice-booking',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMyBookingsRoute = PublicMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => PublicRoute,
} as any)
const PublicChatRoute = PublicChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsIndexRoute = AdminTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundRequestsIndexRoute =
  AdminRefundRequestsIndexRouteImport.update({
    id: '/refund-requests/',
    path: '/refund-requests/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProvidersIndexRoute = AdminProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsIndexRoute = AdminLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesIndexRoute = AdminBusesIndexRouteImport.update({
  id: '/buses/',
  path: '/buses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusTypesIndexRoute = AdminBusTypesIndexRouteImport.update({
  id: '/bus-types/',
  path: '/bus-types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => AdminRoute,
} as any)
const PublicTripsTripIdRoute = PublicTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPaymentBookingCodeRoute =
  PublicPaymentBookingCodeRouteImport.update({
    id: '/payment/$bookingCode',
    path: '/payment/$bookingCode',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/chat': typeof PublicChatRoute
  '/my-bookings': typeof PublicMyBookingsRoute
  '/search': typeof PublicSearchRoute
  '/voice-booking': typeof PublicVoiceBookingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/': typeof PublicIndexRoute
  '/payment/$bookingCode': typeof PublicPaymentBookingCodeRoute
  '/trips/$tripId': typeof PublicTripsTripIdRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/bus-types': typeof AdminBusTypesIndexRoute
  '/admin/buses': typeof AdminBusesIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
  '/admin/providers': typeof AdminProvidersIndexRoute
  '/admin/refund-requests': typeof AdminRefundRequestsIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/chat': typeof PublicChatRoute
  '/my-bookings': typeof PublicMyBookingsRoute
  '/search': typeof PublicSearchRoute
  '/voice-booking': typeof PublicVoiceBookingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/': typeof PublicIndexRoute
  '/payment/$bookingCode': typeof PublicPaymentBookingCodeRoute
  '/trips/$tripId': typeof PublicTripsTripIdRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/bus-types': typeof AdminBusTypesIndexRoute
  '/admin/buses': typeof AdminBusesIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
  '/admin/providers': typeof AdminProvidersIndexRoute
  '/admin/refund-requests': typeof AdminRefundRequestsIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_public/chat': typeof PublicChatRoute
  '/_public/my-bookings': typeof PublicMyBookingsRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/voice-booking': typeof PublicVoiceBookingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/payment/$bookingCode': typeof PublicPaymentBookingCodeRoute
  '/_public/trips/$tripId': typeof PublicTripsTripIdRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/bus-types/': typeof AdminBusTypesIndexRoute
  '/admin/buses/': typeof AdminBusesIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
  '/admin/providers/': typeof AdminProvidersIndexRoute
  '/admin/refund-requests/': typeof AdminRefundRequestsIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/register'
    | '/chat'
    | '/my-bookings'
    | '/search'
    | '/voice-booking'
    | '/admin/dashboard'
    | '/'
    | '/payment/$bookingCode'
    | '/trips/$tripId'
    | '/admin/bookings/$bookingId'
    | '/admin/bookings'
    | '/admin/bus-types'
    | '/admin/buses'
    | '/admin/locations'
    | '/admin/providers'
    | '/admin/refund-requests'
    | '/admin/trips'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/register'
    | '/chat'
    | '/my-bookings'
    | '/search'
    | '/voice-booking'
    | '/admin/dashboard'
    | '/'
    | '/payment/$bookingCode'
    | '/trips/$tripId'
    | '/admin/bookings/$bookingId'
    | '/admin/bookings'
    | '/admin/bus-types'
    | '/admin/buses'
    | '/admin/locations'
    | '/admin/providers'
    | '/admin/refund-requests'
    | '/admin/trips'
    | '/admin/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/admin'
    | '/_auth/login'
    | '/_auth/register'
    | '/_public/chat'
    | '/_public/my-bookings'
    | '/_public/search'
    | '/_public/voice-booking'
    | '/admin/dashboard'
    | '/_public/'
    | '/_public/payment/$bookingCode'
    | '/_public/trips/$tripId'
    | '/admin/bookings/$bookingId'
    | '/admin/bookings/'
    | '/admin/bus-types/'
    | '/admin/buses/'
    | '/admin/locations/'
    | '/admin/providers/'
    | '/admin/refund-requests/'
    | '/admin/trips/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/voice-booking': {
      id: '/_public/voice-booking'
      path: '/voice-booking'
      fullPath: '/voice-booking'
      preLoaderRoute: typeof PublicVoiceBookingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/my-bookings': {
      id: '/_public/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof PublicMyBookingsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/chat': {
      id: '/_public/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof PublicChatRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips/': {
      id: '/admin/trips/'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refund-requests/': {
      id: '/admin/refund-requests/'
      path: '/refund-requests'
      fullPath: '/admin/refund-requests'
      preLoaderRoute: typeof AdminRefundRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers/': {
      id: '/admin/providers/'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations/': {
      id: '/admin/locations/'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses/': {
      id: '/admin/buses/'
      path: '/buses'
      fullPath: '/admin/buses'
      preLoaderRoute: typeof AdminBusesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bus-types/': {
      id: '/admin/bus-types/'
      path: '/bus-types'
      fullPath: '/admin/bus-types'
      preLoaderRoute: typeof AdminBusTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/trips/$tripId': {
      id: '/_public/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof PublicTripsTripIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/payment/$bookingCode': {
      id: '/_public/payment/$bookingCode'
      path: '/payment/$bookingCode'
      fullPath: '/payment/$bookingCode'
      preLoaderRoute: typeof PublicPaymentBookingCodeRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicChatRoute: typeof PublicChatRoute
  PublicMyBookingsRoute: typeof PublicMyBookingsRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicVoiceBookingRoute: typeof PublicVoiceBookingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPaymentBookingCodeRoute: typeof PublicPaymentBookingCodeRoute
  PublicTripsTripIdRoute: typeof PublicTripsTripIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicChatRoute: PublicChatRoute,
  PublicMyBookingsRoute: PublicMyBookingsRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicVoiceBookingRoute: PublicVoiceBookingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPaymentBookingCodeRoute: PublicPaymentBookingCodeRoute,
  PublicTripsTripIdRoute: PublicTripsTripIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminBusTypesIndexRoute: typeof AdminBusTypesIndexRoute
  AdminBusesIndexRoute: typeof AdminBusesIndexRoute
  AdminLocationsIndexRoute: typeof AdminLocationsIndexRoute
  AdminProvidersIndexRoute: typeof AdminProvidersIndexRoute
  AdminRefundRequestsIndexRoute: typeof AdminRefundRequestsIndexRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminBusTypesIndexRoute: AdminBusTypesIndexRoute,
  AdminBusesIndexRoute: AdminBusesIndexRoute,
  AdminLocationsIndexRoute: AdminLocationsIndexRoute,
  AdminProvidersIndexRoute: AdminProvidersIndexRoute,
  AdminRefundRequestsIndexRoute: AdminRefundRequestsIndexRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
